package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"
	"ms-workspace/gateway/internal/delivery/graphql/graph/model"
	go_proto "ms-workspace/package/proto/ms-user/v1/go-proto"
)

// MyInfo is the resolver for the myInfo field.
func (r *queryResolver) MyInfo(ctx context.Context) (*model.MyInfo, error) {
	ss := ctx.Value("session")
	if ss == nil {
		return nil, fmt.Errorf("session is nil")
	}
	session, ok := ss.(*go_proto.AuthenticationResponse)
	if !ok {
		return nil, fmt.Errorf("session is not AuthenticationResponse")
	}
	return &model.MyInfo{
		ID:          int(session.Id),
		Email:       session.Email,
		PhoneNumber: session.PhoneNumber,
		FirstName:   session.FirstName,
		LastName:    session.LastName,
		Status:      session.Status,
	}, nil
}
