gen proto:
	protoc --go_out=./proto/ms-user/v1 --go-grpc_out=./proto/ms-user/v1 ./proto/ms-user/v1/*.proto
	protoc --go_out=./proto/ms-notification/v1 --go-grpc_out=./proto/ms-notification/v1 ./proto/ms-notification/v1/*.proto


